[package]
name = "precommit"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.10.0"
futures = "0.3.30"
git2 = "0.19.0"
lexopt = "0.3.0"
smol = "2.0.2"
thiserror = "1.0.64"

[dev-dependencies]
tempfile = "3.13.0"
